
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                        Version T-2022.03-SP2                         ***
***                      (0.7745337, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2022 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'login02' by user 'banotht.scee.iitmandi'
Binary '/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 -job 1 -swb_pid 22082 -gsub_pid 24721 -gsub_host login02 -gsub_port 37283 /home/banotht.scee.iitmandi/3D_CFET'
Current directory '/home/banotht.scee.iitmandi/3D_CFET'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/..
	STRELEASE=current
	STROOT_LIB=/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/lib
	STDB=/home/banotht.scee.iitmandi
	DATEX=/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/lib/datexcodes.txt
	DISPLAY=172.10.2.5:12.0

Project '/home/banotht.scee.iitmandi/3D_CFET'
Loading global tool database '/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/lib/glib2/tooldb.tcl'
INITIALIZING PREPROCESSOR:
Application mode: traditional
Loading project tree '/home/banotht.scee.iitmandi/3D_CFET/gtree.dat'
Loading jobs and dependence graph '"/home/banotht.scee.iitmandi/3D_CFET/gexec.cmd"'
Loading project variables '/home/banotht.scee.iitmandi/3D_CFET/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/banotht.scee.iitmandi/3D_CFET/sde_dvs.cmd
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/banotht.scee.iitmandi/3D_CFET/sde_dvs.cmd for node 1
+++Preprocessing results written to /home/banotht.scee.iitmandi/3D_CFET/pp1_dvs.cmd
Executing 'sde' binary in original user environment
Start Simulation section
08:41:33 Mar 21 2026     job 1 <sde> started on host 'login02': "sde -l n1_dvs.cmd"
08:56:56 Mar 21 2026 +++ job 1 <sde> done: exit(0)
End Simulation section
Start Epilogue section
08:56:56 Mar 21 2026 *** job 1 pre/post execution: eval " gjob::find_extracted_vars "/home/banotht.scee.iitmandi/3D_CFET" n1_dvs.out 1 "
End Epilogue section
Job succeeded
gjob exits with status 0
