
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                        Version T-2022.03-SP2                         ***
***                      (0.7745337, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2022 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'login02' by user 'banotht.scee.iitmandi'
Binary '/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 1 -job 2 -swb_pid 61302 -gsub_pid 62552 -gsub_host login02 -gsub_port 37371 /home/banotht.scee.iitmandi/mosfet_tutorial'
Current directory '/home/banotht.scee.iitmandi/mosfet_tutorial'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/..
	STRELEASE=current
	STROOT_LIB=/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/lib
	STDB=/home/banotht.scee.iitmandi
	DATEX=/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/lib/datexcodes.txt
	DISPLAY=172.10.2.5:18.0

Project '/home/banotht.scee.iitmandi/mosfet_tutorial'
Loading global tool database '/home/apps/swb/synopsys_tcad/sentaurus/T-2022.03-SP2/bin/../tcad/current/lib/glib2/tooldb.tcl'
INITIALIZING PREPROCESSOR:
Application mode: traditional
Loading project tree '/home/banotht.scee.iitmandi/mosfet_tutorial/gtree.dat'
Loading jobs and dependence graph '"/home/banotht.scee.iitmandi/mosfet_tutorial/gexec.cmd"'
Loading project variables '/home/banotht.scee.iitmandi/mosfet_tutorial/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/banotht.scee.iitmandi/mosfet_tutorial/sdevice_des.cmd
Reading file /home/banotht.scee.iitmandi/mosfet_tutorial/sdevice.par
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/banotht.scee.iitmandi/mosfet_tutorial/sdevice_des.cmd for node 2
+++Preprocessing results written to /home/banotht.scee.iitmandi/mosfet_tutorial/pp2_des.cmd
---------------------------------------
Preprocessing file /home/banotht.scee.iitmandi/mosfet_tutorial/sdevice.par for node 2
+++Preprocessing results written to /home/banotht.scee.iitmandi/mosfet_tutorial/pp2_des.par
Executing 'sdevice' binary in original user environment
Start Simulation section
22:42:45 Dec 24 2025     job 2 <sdevice> started on host 'login02': "sdevice --max_threads 1  pp2_des.cmd"
22:43:08 Dec 24 2025 +++ job 2 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
22:43:08 Dec 24 2025 *** job 2 pre/post execution: eval " gjob::find_extracted_vars "/home/banotht.scee.iitmandi/mosfet_tutorial" n2_des.out 2 "
End Epilogue section
Job succeeded
gjob exits with status 0
